language: cpp
matrix:
  include:
  # - os: linux
    # dist: trusty
  - os: linux
    dist: xenial
  - os: linux
    dist: bionic
before_install: wget https://raw.github.com/tdulcet/Linux-System-Information/master/info.sh -qO - | bash -s --
install:
  - sudo apt-get -yqq update
  - sudo apt-get -yqq install cppcheck autopoint texinfo gperf
  - DIRNAME=$PWD
  - git clone --depth 1 https://github.com/coreutils/coreutils.git
  - git clone https://github.com/coreutils/gnulib.git
  - GNULIB_SRCDIR="$PWD/gnulib"
  - cd coreutils/
  - ./bootstrap --gnulib-srcdir="$GNULIB_SRCDIR"
  - ./configure --disable-gcc-warnings
  - make -j "$(nproc)" CFLAGS="-g -fsanitize=address"
  - ASAN_OPTIONS=detect_leaks=0 travis_wait 30 unbuffer make -j "$(nproc)" check CFLAGS="-g -fsanitize=address" RUN_EXPENSIVE_TESTS=yes RUN_VERY_EXPENSIVE_TESTS=yes || true
  - cp ./src/factor "$DIRNAME/"
  - cd "$DIRNAME/"
  - sed -i 's/"factor"/".\/factor"/' numbers.cpp
script:
  - g++ -std=c++11 -Wall -g -fsanitize=address numbers.cpp -o gcc_numbers
  - ./gcc_numbers --help
  - g++ -std=c++11 -Wall -g -fsanitize=address numbers.cpp -o gcc_gmp_numbers -DHAVE_GMP -lgmpxx -lgmp
  - ./gcc_gmp_numbers --help
  - clang++ -std=c++11 -Wall -g -fsanitize=address numbers.cpp -o clang_numbers
  - ./clang_numbers --help
  - clang++ -std=c++11 -Wall -g -fsanitize=address numbers.cpp -o clang_gmp_numbers -DHAVE_GMP -lgmpxx -lgmp
  - ./clang_gmp_numbers --help
  - cppcheck --enable=all -i coreutils -i gnulib .
