name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  Linux:
    name: Linux

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        cxx: [g++, clang++]
      fail-fast: false
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v3
    - name: Before script
      run: |
        wget https://raw.github.com/tdulcet/Linux-System-Information/master/info.sh -qO - | bash -s --
        sudo apt-get -yqq update
        sudo apt-get -yqq install cppcheck
        $CXX --version
    - name: Script
      run: |
        $CXX -std=c++11 -Wall -g -fsanitize=address,undefined numbers.cpp -o numbers
        ./numbers --help
        $CXX -std=c++11 -Wall -g -fsanitize=address,undefined numbers.cpp -o gmp_numbers -DHAVE_GMP -lgmpxx -lgmp
        ./gmp_numbers --help
    - name: Cppcheck
      run: cppcheck --enable=all .

